### ISSUE TITLE
Keypoint Estimation Subnet

### ISSUE THREAD

**Issue by 994374821** [salihkaragoz/pose-residual-network-pytorch#2]
Does this code contain the implementation of Keypoint Estimation Subnet? And how to add a loss at each level of K features in Keypoint Estimation Subnet? Thanks!

**Comment by FoolishMao** [comment]
@994374821  I am also confused about this. Do you have any ideas?

**Comment by mkocabas** [comment]
> Does this code contain the implementation of Keypoint Estimation Subnet?

Keypoint Subnet isn't included in this repo since we use custom keypoint and person detection methods borrowed from previous works.

> How to add a loss at each level of K features in Keypoint Estimation Subnet?

Sorry for the vague explanation in the paper. We downsample the each K-level features to N (number of keypoints) by using 1x1 convolutions and then upsample the output to match the size of GT heatmaps. You can easily calculate the loss using predicted heatmaps.
